version: '3.0'

services:
  circuit_breaker:
    build: 
      context: ./circuit_breaker
    container_name: circuit_breaker-app
    ports:
      - "81:8000"
    environment:
      - EXTERNAL_SERVICE_URL=http://test-app:8000/
      - MAX_FAILURES=3
      - RESET_TIMEOUT=10

  retry-muster:
    build: 
      context: ./retry_pattern
    container_name: retry_pattern-app
    ports:
      - "82:8000"
    environment:
      - EXTERNAL_SERVICE_URL=http://test-app:8000/

networks:
  default:
    name: test-network
