name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 2: Build Docker images
    - name: Build apps
      run: |
        docker build -t circuit_breaker:latest ./circuit_breaker
        docker build -t fallback_strategy:latest ./fallback_strategy
        docker build -t retry_pattern:latest ./retry_pattern

    # Step 3: Run apps
    - name: Run circuit_breaker app
      run: |
        docker run -d -p 80:8000 --name circuit_breaker-app circuit_breaker:latest

    - name: Run retry_pattern app
      run: |
        docker run -d -p 82:8000 --name retry_pattern-app retry_pattern:latest
      
    - name: Run fallback_strategy app
      run: |
        docker run -d -p 81:8000 --name fallback_strategy-app fallback_strategy:latest
